basePath: /
info:
  contact: {}
  description: Apache Answer API
  title: Apache Answer
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
